### PR TITLE
Update Node to v0.12

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to sgmap/mes-aides-api#37

### CODE REVIEW

**Comment by MattiSG** [comment]
I keep getting errors on a `concat` in the mapping. Could you please try to access the “OpenFisca request“ of a Ludwig test and try to reproduce the bug I encounter?

**Comment by fpagnoux** [comment]
Ok, i'm looking at it

**Comment by MattiSG** [comment]
Whenever I try to simulate, I get:

```
TypeError: Cannot read property 'concat' of undefined
    at /Users/sgmap/Dev/mes-aides-api/lib/simulation/openfisca/mapping/index.js:191:54
    at Function.map (/Users/sgmap/Dev/mes-aides-api/node_modules/lodash/dist/lodash.js:3508:27)
    at exports.mapIndividus (/Users/sgmap/Dev/mes-aides-api/lib/simulation/openfisca/mapping/index.js:177:14)
    at Object.exports.buildOpenFiscaRequest (/Users/sgmap/Dev/mes-aides-api/lib/simulation/openfisca/mapping/index.js:231:28)
    at calculate (/Users/sgmap/Dev/mes-aides-api/lib/simulation/openfisca/index.js:13:23)
    at Object.simulate (/Users/sgmap/Dev/mes-aides-api/lib/simulation/openfisca/index.js:27:5)
    at model.SituationSchema.methods.simulate (/Users/sgmap/Dev/mes-aides-api/lib/models/situation.js:214:19)
    at exports.simulation (/Users/sgmap/Dev/mes-aides-api/lib/controllers/situations.js:51:19)
    at Layer.handle [as handle_request] (/Users/sgmap/Dev/mes-aides-api/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/sgmap/Dev/mes-aides-api/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/sgmap/Dev/mes-aides-api/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/sgmap/Dev/mes-aides-api/node_modules/express/lib/router/layer.js:82:5)
    at /Users/sgmap/Dev/mes-aides-api/node_modules/express/lib/router/index.js:267:22
    at param (/Users/sgmap/Dev/mes-aides-api/node_modules/express/lib/router/index.js:340:14)
    at paramCallback (/Users/sgmap/Dev/mes-aides-api/node_modules/express/lib/router/index.js:391:21)
    at Query.<anonymous> (/Users/sgmap/Dev/mes-aides-api/lib/controllers/situations.js:17:9)
```

(with `npm install && grunt build && npm start`)

**Comment by MattiSG** [comment]
My sgmap/openfisca version is 01cb3b7.

**Comment by fpagnoux** [comment]
I was looking at it, I have the same error

**Comment by MattiSG** [comment]
Ok. I can help on the JS this afternoon if needed.

**Comment by fpagnoux** [comment]
Ok, here is summary of the problem : 
```js
individu = { nationalite: 'fr',
  tauxInvalidite: 'moins80',
  role: 'demandeur',
  dateDeNaissance: Sat Jun 09 1951 02:00:00 GMT+0200 (CEST),
  _id: 556885d1738ea23326b34acd,
  interruptedRessources: [],
  ressources: [],
  situationsPro: [ { situation: 'handicap', _id: 556886339dd4d93c26de7d55 } ] }
```
```js
situation.patrimoine = { revenusLocatifs: [], revenusDuCapital: [] }
```
but 
```js
_.extend(individu, situation.patrimoine) =  { revenusLocatifs: [], revenusDuCapital: [] }
```

**Comment by fpagnoux** [comment]
The problem is not related to this PR, but to the use of node 12. 
Doesn't seem fun at all.

**Comment by MattiSG** [comment]
Nope, it's a problem introduced in `mes-aides-api`. I can run `master` on Node 0.12 without problems.

**Comment by MattiSG** [comment]
Closing. Not a problem in production atm.

**Pull request closed without merging**
