### PR TITLE
Fix bug creation test and cerfa

### PR DESCRIPTION
**Pull request by fpagnoux**

### CODE REVIEW

**Comment by MattiSG** [comment]
Have you tested the Cerfa generation with and without this change?

**Comment by fpagnoux** [comment]
Not, I haven't tested Cerfa

**Comment by MattiSG** [comment]
Ok, I'll do it.

**Comment by MattiSG** [comment]
Indeed, there's no link to the Cerfas anymore… Good catch. I'm now double-checking all other links to Cerfa.

We really need integration tests.

**Comment by MattiSG** [comment]
Fixed via #73 (cherry-picked this PR).

**Pull request closed without merging**
