### PR TITLE
Use Bootstrap class for screenReadersOnly CSS

### PR DESCRIPTION
**Pull request by MattiSG**
@fpagnoux was there any specific reason for introducing that class rather than using Bootstrap's default one?

### CODE REVIEW

**Comment by fpagnoux** [comment]
Didn't know it existed. Is the implementation the same ? Did you check the behaviour ?

**Comment by MattiSG** [comment]
[Same implementation](https://github.com/twbs/bootstrap/blob/4e163001358170c747e3443982e15dc41d3dcabe/less/scaffolding.less#L125-L134), behaviour is the same with VoiceOver.

**Comment by MattiSG** [comment]
@fpagnoux GTM ?

**Comment by fpagnoux** [comment]
GTM

**Pull request merged**
